CREATE DATABASE THI_THU
GO
USE THI_THU
GO

CREATE TABLE SINHVIEN
(
	MASV INT IDENTITY(0,1) PRIMARY KEY,
	TENSV NVARCHAR(30) NOT NULL,
	KHOA NVARCHAR(30) NOT NULL,
	NGAYSINH DATE,
)

CREATE TABLE MONHOC
(
	MAMON INT IDENTITY(0,1) PRIMARY KEY,
	TENMON NVARCHAR(30) NOT NULL DEFAULT N'Tên môn học',
	SOTC INT NOT NULL,
)

CREATE TABLE DIEM
(
	DIEMKT FLOAT NOT NULL,
	DIEMTHI FLOAT NOT NULL,
	DIEMTK FLOAT NOT NULL,
	NAMHOC INT NOT NULL,
	HOCKY INT NOT NULL,
	MASV INT,
	MAMON INT,

	FOREIGN KEY(MASV) REFERENCES dbo.SINHVIEN(MASV) ON DELETE CASCADE,
	FOREIGN KEY(MAMON) REFERENCES dbo.MONHOC(MAMON) ON DELETE CASCADE,
)

INSERT INTO SINHVIEN(TENSV,KHOA,NGAYSINH) VALUES(N'Nguyễn Phạm Thành Hưng',N'Công Nghệ Thông Tin','2002/9/16');


SELECT SINHVIEN.MASV,MONHOC.MAMON,DIEM.DIEMTK 
FROM SINHVIEN,DIEM,MONHOC
WHERE SINHVIEN.MASV=1